[job]
dump_folder = "./outputs"
description = "Llama 4 Dense XPU Benchmark"

[profiling]
enable_profiling = false
save_traces_folder = "profile_trace"
profile_freq = 100

[metrics]
log_freq = 1
enable_tensorboard = false
save_tb_folder = "tb"

[model]
name = "llama4"
flavor = "debugmodel_dense"
tokenizer_path = "tests/assets/test_tiktoken.model"

[optimizer]
name = "AdamW"
lr = 8e-4

[training]
batch_size = 32
seq_len = 512
warmup_steps = 2
max_norm = 1.0
steps = 10
data_parallel_replicate_degree = 1
data_parallel_shard_degree = 1
tensor_parallel_degree = 1
pipeline_parallel_degree = 1
expert_parallel_degree = 1
compile = false
dataset = "c4_test"

[experimental]
context_parallel_degree = 1
pipeline_parallel_split_schedule = "V"

[checkpoint]
enable_checkpoint = false
folder = "checkpoint"
interval_type = "steps"
interval = 500
model_weights_only = false
export_dtype = "float32"
async_mode = "disabled"

[activation_checkpoint]
mode = 'selective'
selective_ac_option = 'op'
