[job]
dump_folder = "./outputs"
description = "Llama 4 FSDP-only XPU Benchmark (No EP)"

[profiling]
enable_profiling = false
save_traces_folder = "profile_trace"
profile_freq = 100

[metrics]
log_freq = 1
enable_tensorboard = false
save_tb_folder = "tb"

[model]
name = "llama4"
flavor = "debugmodel"
hf_assets_path = "/home/ngetty/proj/vllm_gpt-oss/Aurora-Inferencing/torchtitan_xpu/torchtitan/tests/assets/tokenizer"
use_triton_moe = false

[optimizer]
name = "AdamW"
lr = 8e-4

[training]
local_batch_size = 32
seq_len = 512

max_norm = 1.0
steps = 5


dataset = "c4_test"
dataset_path = "/home/ngetty/proj/vllm_gpt-oss/Aurora-Inferencing/torchtitan_xpu/torchtitan/tests/assets/c4_test"

[parallelism]
data_parallel_replicate_degree = 1
data_parallel_shard_degree = 2
tensor_parallel_degree = 1
pipeline_parallel_degree = 1
context_parallel_degree = 1
expert_parallel_degree = 1

[lr_scheduler]
warmup_steps = 2

[compile]
enable = false

[checkpoint]

[activation_checkpoint]
mode = "selective"
selective_ac_option = "op"
