# Llama4 Large Dense Equivalent 4k MFU Benchmark
# Using Batch=2, Seq=2048 (4,096 tokens/rank) to avoid OOM seen at 8,192 tokens.
# Using Full Activation Checkpointing.

[job]
dump_folder = "./outputs_llama4_large_dense_equivalent_4k"
description = "Llama 4 Large Dense Equivalent 4k Tokens/Rank Full AC benchmark on XPU"

[profiling]
enable_profiling = false

[metrics]
log_freq = 1
enable_tensorboard = false

[model]
name = "llama4"
flavor = "largemodel_dense_equivalent"
tokenizer_path = "/home/ngetty/proj/vllm_gpt-oss/Aurora-Inferencing/torchtitan_xpu/torchtitan/tests/assets/tokenizer"
use_triton_moe = false

[optimizer]
name = "AdamW"
lr = 3e-4

[training]
local_batch_size = 2
seq_len = 2048
max_norm = 1.0
steps = 10
mixed_precision_param = "bfloat16"
mixed_precision_reduce = "float32"

dataset = "c4_test"
dataset_path = "/home/ngetty/proj/vllm_gpt-oss/Aurora-Inferencing/torchtitan_xpu/torchtitan/tests/assets/c4_test"

[lr_scheduler]
warmup_steps = 2

[activation_checkpoint]
mode = "full"

[parallelism]
data_parallel_replicate_degree = 1
data_parallel_shard_degree = 12
tensor_parallel_degree = 1
expert_parallel_degree = 1
pipeline_parallel_degree = 1

[compile]
enable = false
